---
commitizen:
  name: cz_conventional_commits
  tag_format: v$version
  version_scheme: semver
  version_provider: commitizen
  update_changelog_on_bump: true
  major_version_zero: true
  update_files:
    - docker-compose.yml:v$current_version:v$new_version
