"""
Django settings for pinpoint project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from .dbconfig import SQLITE_ENGINE, database_config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-%*55ducb_um2tim9z^4kibc6n5014t53-a1fqp@nsd1&e_04se",
)

DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost 127.0.0.1").split()

CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split()


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ebhealthcheck",
    "game",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves everything under STATIC_ROOT. Without this the admin has no CSS in
    # production: gunicorn only runs the WSGI app, and Django itself refuses to
    # serve static files once DEBUG is off.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pinpoint.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pinpoint.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Postgres (RDS) when a database host is configured, SQLite otherwise.
# See pinpoint/dbconfig.py for the environment variables involved.
DATABASES = {"default": database_config(base_dir=BASE_DIR)}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en"

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ("en", _("English")),
    ("nl", _("Dutch")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Files served from the site root rather than under STATIC_URL, so that
# /favicon.ico works for clients that ask for it directly.
WHITENOISE_ROOT = BASE_DIR / "public"

if not DEBUG:
    # Hashed filenames plus pre-compressed copies, so static assets can be
    # cached indefinitely. Only outside DEBUG: the manifest is written by
    # collectstatic, and requiring it locally would break `runserver`.
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if os.environ.get("USE_S3", "false").lower() == "true":
    INSTALLED_APPS += ["storages"]
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")
    if os.environ.get("AWS_ACCESS_KEY_ID", None):
        print("setting AWS credentials")
        AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
        AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]

# SQLite-on-S3 persistence
#
# The container downloads the database on start and uploads it again after
# writes, which is only safe with a SINGLE instance -- two containers would each
# hold their own copy and the last upload would silently discard the other's
# writes. Ignored unless SQLite is the backend.
SQLITE_S3_BUCKET = os.environ.get("SQLITE_S3_BUCKET", "")
SQLITE_S3_KEY = os.environ.get("SQLITE_S3_KEY", "db/db.sqlite3")
# Touched by a signal after every write; the entrypoint's loop watches for it.
SQLITE_DIRTY_MARKER = os.environ.get("SQLITE_DIRTY_MARKER", "/tmp/pinpoint-db-dirty")
SQLITE_S3_SYNC = bool(SQLITE_S3_BUCKET) and DATABASES["default"]["ENGINE"] == SQLITE_ENGINE


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
