# Generated by Django 4.2.30 on 2026-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypoint",
            name="advance_type",
            field=models.CharField(
                choices=[
                    ("button", "Button"),
                    ("question", "Question / Riddle"),
                    ("proximity", "Auto-proximity"),
                ],
                default="button",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="answer",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="proximity_meters",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="question",
            field=models.TextField(blank=True),
        ),
    ]
