# Generated by Django 4.2.30 on 2026-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_waypoint_advance_type_waypoint_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypoint",
            name="button_caption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="button_text",
            field=models.TextField(blank=True),
        ),
    ]
