# Generated by Django 4.2.30 on 2026-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_waypoint_button_caption_waypoint_button_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
