# Generated by Django 4.2.30 on 2026-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_route_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypoint",
            name="image",
            field=models.ImageField(blank=True, upload_to="waypoints/"),
        ),
    ]
