# Generated by Django 4.2.30 on 2026-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_waypoint_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="completion_emoji",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="route",
            name="completion_message",
            field=models.TextField(blank=True),
        ),
    ]
