# Generated by Django 4.2.30 on 2026-09-10 12:20

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_completion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waypoint",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=game.models.waypoint_image_path
            ),
        ),
    ]
