# Generated by Django 4.2.30 on 2026-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_waypoint_image_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waypoint",
            name="proximity_meters",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
