# Generated by Django 4.2.30 on 2026-09-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="waypoint",
            name="require_correct_answer",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=500)),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="game.participant",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="game.waypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["waypoint__order"],
            },
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("participant", "waypoint"),
                name="unique_answer_per_participant_waypoint",
            ),
        ),
    ]
